import type { NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import styles from "../styles/Home.module.css";

const Home: NextPage = () => {
    return (
        <div className="min-h-screen bg-gray-50 relative overflow-hidden">
            <Head>
                <title>TigerTix</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <header className="w-full h-24 bg-gradient-to-r from-orange to-blood rounded-b-md flex items-center justify-center md:justify-start">
                <h1 className="text-4xl italic bold text-white text-opacity-90 md:pl-6">
                    TigerTix
                </h1>
            </header>
            <main className={"container mx-auto p-2 " + styles.main}>
                <section className="venues ml-4 mt-4">
                    <h1 className="text-2xl with-icon">
                        <Link href="/venues">
                            <a className="with-icon group">
                                Venues
                                <svg
                                    xmlns="http://www.w3.org/2000/svg"
                                    className="h-6 w-6 group-hover:ml-3 ml-2 transition-all"
                                    fill="none"
                                    stroke="currentColor"
                                    strokeWidth={2}
                                >
                                    <path
                                        strokeLinecap="round"
                                        strokeLinejoin="round"
                                        d="M14 5l7 7m0 0l-7 7m7-7H3"
                                    />
                                </svg>
                            </a>
                        </Link>
                    </h1>
                </section>
            </main>
        </div>
    );
};

export default Home;
